### PR TITLE
Update chess.lua

### PR DESCRIPTION
**Pull request by zerfgog**
y

### CODE REVIEW

**Comment by SwadicalRag** [comment]
+1

also i donated on patereon where is my sculpture of hash??
i will report if i dont get

**Comment by YourStalker** [comment]
10/10.1

**Comment by zerfgog** [comment]
888888888888888888888888888888888888888888888888888888888888
88OZOZZZZZOZZZ8OZOOOZODOZZZOZ8ZOOOOO8OOZZZZO8OZZZZZZZOZOO888
88Z$$$$$$$$$$$8$$$$$$ZD$$$$$$8$$$$$$8O$$$$$$D$$$$$$$$$$$Z888
88Z$$$$$$$$$$$O$$$$$$Z8$$$$$$8$$$$$$8O$$$$$$8$$$$$$$$$$$Z888
88Z$$$$$$$$$$$8888888DD888888888888888888888D$$$$$$$$$$$Z888
88Z$$$$$$$$$$$O:,,:::+8$$$$$$8$$$$$$8?:::,,:8$$$$$$$$$$$Z888
88Z$$$$$$$$$$$O:,:,:,+8$$$$$$8$$$$$$8?,:::::8$$$$$$$$$$$Z888
88Z$$$$$$$$$$$8:,:,,:+8$$$$$$8$$$$$$8?::,,::8$$$$$$$$$$$Z888
88O$$$$$$$$$$$8:,,,,,=8$$$$$$D$$$$$$D?,,,,,:8$$$$$$$$$$$Z888
88888O88$$$$$$87$$$$ZZD$$$$$$D$$$$$$DOZ$$$$$8$$$$$$888888888
88Z$$$$8,:,:::$~:,:::+N:::::,M,:::::DI:::,:~D:::::,8$$$$Z888
88Z$$$$8,,,:::Z:,:,,,+M,::::,M,,,,,,N?:::,::D:,,:,,D$$$$Z888
88Z$$$$8,,,:::Z:,:,:,+M,:::,,M,::,,,N?:::,::D:::::,D$$$$Z888
88OZZZZD=++++=Z?==++=IN=+++++N=++++=8$+++=+?D+++++=DZZZZO888
88Z$$$$8$$$$$$8:,,,,,=8$$$$$$8$$$$$$8?,,,,,:8$$$$$$8$$$$Z888
88Z$$$$8$$$$$$8::::::+8$$$$$$D$$$$$$8?::::::8$$$$$$8$$$$Z888
88Z$$$$8$$$$$$8:,::::+8$$$$$$8$$$$$$8?::::::8$$$$$$8$$$$Z888
88Z$$$$8$$$$$$O:,,,,:+8$$$$$$8$$$$$$8?,:::::8$$$$$$8$$$$Z888
8888D8D8DD88888NNNNNNN8DD888D88888888DNNDNNN88888DD8D8888888
88Z$$$$8$$$$$$8:,:::,+8$$$$$$D$$$$$$8?,:::::8$$$$$$8$$$$Z888
88Z$$$$8$$$$$$8:,:,:,+8$$$$$$D$$$$$$8?,:::::8$$$$$$8$$$$Z888
88Z$$$$8$$$$$$8:,:,:,+8$$$$$$D$$$$$$8?::::::8$$$$$$8$$$$Z888
88Z$$$$8$$$$$$8,,,,,,=8$$$$$$D$$$$$$8?,,,,,:8$$$$$$8$$$$Z888
888OOOO8I????IO7?IIII$D??????N???I??DZIIII?78I????I8OOOOO888
88Z$$$$D,:::::$:,,,,,+M,:,::,M,,,,,,N?,,,,::8:::::,D$$$$Z888
88Z$$$$D,:::,:$:,::::+M::::,,M,::,,,N?:::,::D::,,:,D$$$$Z888
88O$$$$D,:::::$~,,:::+M,::::,M,::,,,DI:,:,,:D:::::.8$$$$O888
88888OO8$$$$$$8$$$$$$ZD$$$$$$D$$$$$$DOZ$$$$78$$$$$$8OO8O8888
88O$$$$$$$$$$78:,,,,,+8$$$$$787$$$$$D?,,,,,:8$$$$$$$$$$$Z888
88Z$$$$$$$$$$$8:,:,::+8$$$$$$8$$$$$$8?,:::::8$$$$$$$$$$$Z888
88Z$$$$$$$$$$$8::::::+8$$$$$$8$$$$$$8?::,,::8$$$$$$$$$$$Z888
88Z$$$$$$$$$$$O:,,::,+8$$$$$$8$$$$$$8?,::,,:O$$$$$$$$$$$Z888
88Z$$$$$$$$$$$8DDDDDDD8DD888DD888888888DDDDD8$$$$$$$$$$$Z888
88Z$$$$$$$$$$$OZ$$$$$Z8$$$$$$8$$$$$$8O$$$$$$8$$$$$$$$$$$Z888
88Z$$$$$$$$$$$8Z$$$$$Z8$$$$$$D$$$$$$8O$$$$$$D$$$$$$$$$$$Z888
88OZZZZZZZZZZZ8ZZZZZZO8ZZZZZZ8ZZZZZZ8OZZZZZZ8ZZZZZZZZZZZO888
888888888888888888888888888888888888888888888888888888888888
D888888888888888888888888888888888888888888888888888888888DO

**Comment by Velkon** [comment]
7#/10#

Low quality.

**Comment by SwadicalRag** [comment]
ok i change my +1 to +2 now tank you very much

very good service

**Pull request merged**
