### PR TITLE
Added image reply user module

### PR DESCRIPTION
**Pull request by SwadicalRag**

### CODE REVIEW

**Comment by SwadicalRag** [comment]
Oops forgot to include it

**Comment by mcd1992** [comment]
That's a lot of dank memes you got there

**Comment by SwadicalRag** [comment]
Why thank you

**Comment by mcd1992** [comment]
Fix your conflicts nub.

**Comment by mcd1992** [comment]
76ddd6c84f05fca315982a96da5e4bff27ea558e

**Pull request closed without merging**
