### PR TITLE
Create fishingsim.lua

### PR DESCRIPTION
**Pull request by zerfgog**

### CODE REVIEW

**Comment by wyozi** [comment]
:fishing_pole_and_fish:

**Comment by zerfgog** [comment]
yes, quite

**Comment by SwadicalRag** [comment]
+1

**Comment by zerfgog** [comment]
thanks for all the support guys, without you I don't know if I would've made it this far <3








remember to donate on patreon

**Comment by notcake** [comment]
+1 wollox merge please

**Pull request merged**
